services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: termbox
    volumes:
    - termbox_demo_003_postgres_data:/var/lib/postgresql
  termbox:
    depends_on:
      - postgres
    image: ghcr.io/healthsamurai/termbox:edge
    pull_policy: always
    ports:
      - "3003:3000"
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: postgres
      PG_MAINTENANCE_WORK_MEM: 512MB
      HTTP_BASE_URL: http://localhost:3003
volumes:
  termbox_demo_003_postgres_data: {}
